export const FOTOS_NUMBER = 25;
export const MAX_COMMENTS_NUMBER = 30;
export const MAX_AVATAR_URL = 6;
export const SHOWN_COMMENTS_NUMBER = 5;
export const MAX_HASHTAG_LENGTH = 19;
export const MAX_HASHTAG_NUMBER = 5;
export const MAX_DESCRIPTION_LENGTH = 140;
export const SCALE_STEP = 25;
export const HASHTAG_RULE_REGEX = new RegExp(`^#[a-zа-яё0-9]{1,${MAX_HASHTAG_LENGTH}}$`, 'i');
